<a href="https://colab.research.google.com/github/ohstopityou/info345-recommender-systems/blob/main/Collaborative_Filtering_for_students.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Collaborative Filtering
This Python Notebook will show a number of collaborative filtering techniques, applied to the Movielens 100K dataset. The data is provided, but split in different files (e.g., users, items, ratings, etc.)

We will cover:

- Simplest mean-rating based CF
- Simplest demographic-based CF
- KNN: k-nearest neightbors
- SVD: Singular value decomposition
- CoClustering algorithm

![pic](https://www.codecademy.com/resources/blog/wp-content/uploads/2022/12/Recommender-System_Recommender-System__Thumbnail.png)

___________

### Let's start with preparing all the data

In [ ]:
# import relevant packages
import pandas as pd
import numpy as np

First, load u.user file which contain user demographics data:

In [ ]:
#Load the u.user file into
u_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code'] # define names for the columns

users = pd.read_csv(  )      # read the data, the scv file is using | separator


#print out first five lines to inspect the data

   user_id  age sex  occupation zip_code
0        1   24   M  technician    85711
1        2   53   F       other    94043
2        3   23   M      writer    32067
3        4   24   M  technician    43537
4        5   33   F       other    15213

__________

Then, load u.item file with movie metadata:

In [ ]:
i_cols = ['movie_id', 'title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
 'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

# read the data, the scv file is using | separator
movies = pd.read_csv(  )

#print out first five lines to inspect the data

,movie_id,title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
# Remove all information except Movie ID and title:
movies = movies[[  ,  ]] # specific features

____

Now, load u.data file which contain user-movie ratings:

In [ ]:
#Load the u.data file
r_cols = ['user_id', 'movie_id', 'rating', 'timestamp']

# read the data, the scv file is using \t separator
ratings = pd.read_csv(  )

#print out first five lines to inspect the data

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

We will not need the timestamps for now so let's just drop it:

In [ ]:
#Drop the timestamp column
ratings = ratings.drop('  ', axis=1)

____

### Separating the data into train and test sets
We will create a model that predicts ratings for movies from 1 to 5. Like in classic machine learning, we would need some data to train on and some data to test our model on. These sets should never intersect, otherwise our system would experience data leakage and will "know" too much about the values it's supposed to predict. Evaluation and performance of such a system cannot be trusted.

In this example, we split 75% of the data in a training set, and 25% of the data in a test set. You are of course free to change these parameters below.

The split is done in a slightly 'hacky' way: we assume that the user_id is the target variable (or Y) and that our ratings dataframe comprises the predictor variables (or x). We will then pass these two varaibles into scikit-learn's train_test_split function and stratify it along y. This ensures that the proportion of each class is the same in both the training and testing datasets:

In [ ]:
#Import the train_test_split function
from sklearn.model_selection import train_test_split

#Assign X as the original ratings dataframe and y as the user_id column of ratings.
X = ratings.copy()
y = ratings['user_id']

#Split into training and test datasets, stratified along user_id
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, stratify=y, random_state=42)

_____

### User-Based Collaborative Filtering

Let's build our rating matrix. The columns represent the movies, the rows represent the users. Each cell is a rating given a user i to a movie j.

In [ ]:
#Build the ratings matrix using pivot_table function
r_matrix = X_train.pivot_table(values='rating', index='user_id', columns='movie_id')

r_matrix.head()

movie_id,1,2,3,4,5,6,7,8,9,10,...,1671,1672,1673,1674,1676,1677,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,NaN,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Mean-rating model

Just with this matrix we can build the simplest collaborative filter possible. We will compute the means of each movie in our training dataset. In doing so, we assume equal weight of each user in determining the rating (Any potential issues with this, by the way?)

If there are no ratings available in either the training or test dataset, we will assume the absolute mean value for that movie: 3.0

In [ ]:
def cf_user_mean(user_id, movie_id):

    #Check if movie_id exists in r_matrix
    if movie_id in r_matrix:
        #Compute the mean of all the ratings given to the movie
        mean_rating = r_matrix[movie_id].mean()
    else:
        #Default to a rating of 3.0 in the absence of any information
        mean_rating = 3.0

    return mean_rating

______

#### Demographic-based collaborative filtering

Demographic collaborative filters rely on the intuition that users with similar backgrounds (age, sex, occupation, etc.) are more likely to have similar tastes. This means that we do not need to take all ratings of all users into account, but only the ratings of those that are relevant to another user.

The first demographic filter we will build simply takes the gender of the user, compute the (weighted) mean rating of a movie by that particular gender, and return that as the predicted value. To obtain this information, we need to merge our rating set with the demographic dataframe.

In [ ]:
#Merge the original users dataframe with the training set
merged_df =

merged_df.head()

   user_id  movie_id  rating  age sex occupation zip_code
0      862       177       4   25   M  executive    13820
1      862       416       3   25   M  executive    13820
2      862      1093       5   25   M  executive    13820
3      862       168       4   25   M  executive    13820
4      862       568       3   25   M  executive    13820

In [ ]:
# Compute the mean rating given by each gender

gender_mean = merged_df[['movie_id', 'sex', 'rating']].groupby(['movie_id', 'sex'])['rating'].mean()

#print out first 10 rows of the result to check it
gender_mean.head(10)

movie_id  sex
1         F      3.797872
          M      3.888446
2         F      3.285714
          M      3.202703
3         F      2.916667
          M      3.245614
4         F      3.545455
          M      3.563025
5         F      3.714286
          M      3.155556
Name: rating, dtype: float64

In [ ]:
#Set the index of the users dataframe to the user_id
users = users.set_index('  ')
users.head()

         age sex  occupation zip_code
user_id
1         24   M  technician    85711
2         53   F       other    94043
3         23   M      writer    32067
4         24   M  technician    43537
5         33   F       other    15213

In [ ]:
#Gender Based Collaborative Filter using Mean Ratings
def cf_gender(user_id, movie_id):

    #Check if movie_id exists in r_matrix (or training set)
    if movie_id in r_matrix:

        #Identify the gender of the user
        gender = users.loc[user_id]['sex']

        #Check if the gender has rated the movie
        if gender in gender_mean[movie_id]:

            #Compute the mean rating given by that gender to the movie
            gender_rating = gender_mean[movie_id][gender]

        else:
            gender_rating = 3.0

    else:
        #Default to a rating of 3.0 in the absence of any information
        gender_rating = 3.0

    return gender_rating

___

### Before we try to evaluate our simple models, let's pause for a second and think about any drawbacks and complications connected to both models. What can be difficult/problematic? What wouldn't work?

____

#### Okay, now let's test it out - evaluation phase!

Root Mean Square Error (RMSE) is the most common metric (minimizing error). We will first use this one. Scikit learn, fortunately, has a lot of handy implementations for metrics.

In [ ]:
#Import the mean_squared_error function
from sklearn.metrics import mean_squared_error

#Function that computes the root mean squared error (or RMSE)
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

In [ ]:
#Function to compute the RMSE score obtained on the testing set by a model
def score(cf_model):

    #Construct a list of user-movie tuples from the testing dataset
    id_pairs = zip(X_test['user_id'], X_test['movie_id'])

    #Predict the rating for every user-movie tuple
    y_pred = np.array([cf_model(user, movie) for (user, movie) in id_pairs])


    #Extract the actual ratings given by the users in the test data
    y_true = np.array(X_test['rating'])

    #Return the final RMSE score
    return rmse(y_true, y_pred)

Often in recommender systems research we define simplest baseline recommender models to compare our methods against - it can be a random recommender, a static one, or a model recommending only top popular items for everyone.

In [ ]:
#Define the baseline model to always predicts a rating of 3
def baseline(user_id, movie_id):
    return 3.0

In [ ]:
# the RMSE score between the baseline model and the actual data

score(#baseline)

1.2488234462885457

In [ ]:
# The RMSE score of Mean based model
score(#mean)

1.0300824802393536

In [ ]:
# The RMSE score of Demographic based model
score(#demographic)

1.0392906999935203

Is this how you expected the models to perform? Any thoughts or impressions are welcome :)

___

## Model Based Approaches
The previous examples with demographics or mean ratings were a bit too simplistic. Machine learning comes to the rescue! Let's try to use now actual proven recommender systems models to see if we can beat the score.


- Using Surprise Library:  Simple Python Recommendation System Engine.
  
    pip3 install scikit-surprise // pip install scikit-surprise

In [ ]:
!pip install scikit-surprise

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Looking in indexes: https://pypi.org/simple, https://anastasiia.klimashevskaia%40tv2.no:****@tv2norge.jfrog.io/tv2norge/api/pypi/ai-python-local/simple
Requirement already satisfied: scikit-surprise in /opt/homebrew/lib/python3.9/site-packages (1.1.3)
Requirement already satisfied: joblib>=1.0.0 in /opt/homebrew/lib/python3.9/site-packages (from scikit-surprise) (1.1.0)
Requirement already satisfied: numpy>=1.17.3 in /opt/homebrew/lib/python3.9/site-packages (from scikit-surprise) (1.21.6)
Requirement already satisfied: scipy>=1.3.2 in /opt/homebrew/lib/python3.9/site-packages (from scikit-surprise) (1.7.3)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python3.9 -m pip install --upgrade pip

Surprise has a lot of handy methods for handling the data, training and evaluation. Let's use some of them:

In [ ]:
#Import the required classes and methods from the surprise library
from surprise import *
from surprise import Reader, Dataset, KNNBasic, SVD, CoClustering
from surprise.model_selection import cross_validate, KFold
from tabulate import tabulate
import time
import datetime


#Define a Reader object
#The Reader object helps in parsing the file or dataframe containing ratings
reader = Reader()

#Create the dataset to be used for building the filter
data = Dataset.load_from_df(#rating matrix, #reader instance)

### K-fold cross validation

![pic](https://miro.medium.com/v2/resize:fit:1200/1*AAwIlHM8TpAVe4l2FihNUQ.png)

This time we will use 5-fold cross validation data split, which randomly takes equal chunks of data out of the dataset in 5 iterations, calculating then the average of the evaluation scores.

In [ ]:
#let's make the random a bit less random
np.random.seed(0)
# split data into Kf_# folds
kf_5 = KFold(n_splits=5, random_state= 0 )


# Helpful function for better visualization
def algo_to_table(algo):
  table_5 = []

  start = time.time()

  # cross validate on 5  folds on two evaluation metrics
  result_5= cross_validate(algo(), data, ['rmse','mae'],kf_5)

  #pretty print out our results in a table
  cv_time = str(datetime.timedelta(seconds=int(time.time() - start)))

  mean_rmse = '{:.3f}'.format(np.mean(result_5['test_rmse']))

  mean_mae = '{:.3f}'.format(np.mean(result_5['test_mae']))

  line = [str(algo.__name__), mean_rmse, mean_mae,cv_time]

  table_5.append(line)
  return table_5

___

<div>
<img src="https://thatgirlcoder.com/wp-content/uploads/2024/02/knn.png" width="500"/>
</div>

We will test out KNNBasic implementation first:

In [ ]:
KNN_Results = algo_to_table(#KNN)

table_header = [str('Algorithm'),'RMSE','MAE','Time']
print(' \n \t -------------------- The result for K = 5 --------------------------- \t \n')
print(tabulate(KNN_Results, table_header, tablefmt="pipe"))

Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.

 	 -------------------- The result for K = 5 ---------------------------

| Algorithm   |   RMSE |   MAE | Time    |
|:------------|-------:|------:|:--------|
| KNNBasic    |   0.98 | 0.774 | 0:00:08 |

____

<div>
<img src="https://cdn.prod.website-files.com/5b1d427ae0c922e912eda447/5feb62f53532cb257a8f901d_open_compressed.jpg" width="500"/>
</div>

Now the SVD model:

In [ ]:
SVD_Results = algo_to_table(#SingularValueDecomposition)

table_header = [str('Algorithm'),'RMSE','MAE','Time']
print(' \n \t -------------------- The result for K = 5 --------------------------- \t \n')
print(tabulate(SVD_Results, table_header, tablefmt="pipe"))

 	 -------------------- The result for K = 5 ---------------------------

| Algorithm   |   RMSE |   MAE | Time    |
|:------------|-------:|------:|:--------|
| SVD         |  0.936 | 0.738 | 0:00:03 |

____

<div>
<img src="https://ars.els-cdn.com/content/image/1-s2.0-S0950705115000593-gr3.jpg" width="500"/>
</div>

- Co-Clustering

In [ ]:
CoClustering_Results = algo_to_table(CoClustering)

table_header = [str('Algorithm'),'RMSE','MAE','Time']
print(' \n \t -------------------- The result for K = 5 --------------------------- \t \n')
print(tabulate(CoClustering_Results, table_header, tablefmt="pipe"))

 	 -------------------- The result for K = 5 ---------------------------

| Algorithm    |   RMSE |   MAE | Time    |
|:-------------|-------:|------:|:--------|
| CoClustering |  0.965 | 0.756 | 0:00:06 |

Remember our baseline models? Have we actually done better with machine learning? Let's check again:

In [ ]:
print("Baseline algorithm RMSE:", score(baseline))
print("Mean-score based algorithm RMSE:", score(cf_user_mean))
print("Gender-based algorithm RMSE:", score(cf_gender))

Baseline algorithm RMSE: 1.2488234462885457
Mean-score based algorithm RMSE: 1.0300824802393536
Gender-based algorithm RMSE: 1.0392906999935203